- hosts: webservers
  gather_facts: false
  name: test things on webservers
  tasks:
    - name: are widgets active?
      assert:
        that: widgets_active|bool

    - name: are gadgets effective?
      assert:
        that: gadgets_effective|bool

- hosts: dbservers
  gather_facts: false
  name: test things on dbservers
  tasks:
    - name: is the pope catholic?
      assert:
        that: true
